### PR TITLE
Change underlying mongodb driver to mongodb-native

### PR DESCRIPTION
**Pull request by liamdon**
This is a PR from our fork of agenda, which replaces mongoskin with mongodb-native and also improves the efficiency of some queries, which would previously not perform well even if indexed. It should fulfill most of the requests posted on issue #156 

This PR is not perfect - ideally we'd like community support to tidy it up and provide better documentation. We are using it in production, but only for a very specific use-case, so we have not touched all code paths, but it does maintain the same test coverage as the mongoskin implementation.

### CODE REVIEW

**Comment by Zertz** [comment]
Seems conflicts are preventing Travis CI from running? This repo is probably some commits ahead on yours, you'll have to merge them into your fork first. Tough to help without tests running

**Comment by liamdon** [comment]
Thanks for the heads up @Zertz - this actually highlighted an important breaking change on this PR, which is that the **mongodb-native upgrade has changed the minimum MongoDB version from 2.4 to 2.6**. I had to edit the travis-ci config to support this.

**Comment by Zertz** [comment]
Awesome! We really need those tests though, isn't it possible to switch out mongoskin for the native driver in tests as well?

**Comment by rschmukler** [comment]
This looks good to me.  I'll squash before merging into master. That being said, @nwkeeley and @droppedoncaprica - do you guys have any comments?

Also, @liamdon I'm always looking to add good maintainers to the project. This was quite a bit of work. Let me know if you have any interest in becoming a maintainer.

**Comment by liamdon** [comment]
Excellent, happy to address any comments. I'd definitely be interested in becoming a maintainer! I think there are still a few areas we can clean up, then perhaps a wider initiative to make the storage backend pluggable.

**Comment by droppedoncaprica** [comment]
I didn't see anything amiss, looks good to go to me.  :+1: 

But seriously guys, really really well done.  Thanks for helping get this in, I've been short on time to work on anything serious.

Figure I'd send a mention to the fine folk that contributed to this patch for being awesome.
@liamdon @chrisckchang @jetzhou @byronmwong @cdolivares

**Comment by rami-prilutsky** [comment]
Hi, are there any plans in pulling this? 
There's one issue I encountered while initializing Agenda prototype with a mongo url, there's an async call to 
```javascript
this.database(config.db.address, config.db.collection, config.db.options);
```
which does
```javascript
MongoClient.connect(url, options, function( error, db ){});
```
and
```javascript
this._collection.createIndexes();
```

So after initializing Agenda prototype the mongo collection isn't immediately ready for use and will fail if accesing it.

**Comment by rschmukler** [comment]
This PR has been merged via a squashed commit in the form of 4246c3bded7864a6896a771f4dacb5b8edee3635 and published as `agenda@0.7.0` on npm. Thank you again classdojo team for all the hard work! Apologies on the delay.

Regarding @rami-prilutsky's comment - we may want to add a callback to agenda after the db has been connected to successfully where configuring can occur. eg. `agenda.connect(function(err) { // do work})`

**Pull request closed without merging**
