### PR TITLE
Including nextRunAt check in query for on the fly lock.

### PR DESCRIPTION
**Pull request by jakeorr**
for #286

### CODE REVIEW

**Comment by loris** [comment]
Very nice! Just tried your branch and it fixes the bug on my side, thanks!

**Comment by jakeorr** [comment]
:+1: :smile:

**Comment by loris** [comment]
@rschmukler would you mind releasing a `0.8.1` patch to npm? `0.8.0` can have critical behavior (sending multiple emails to a single user in my case). Thanks!

**Comment by coox** [comment]
+1 for a `0.8.1` release. Thanks much!

**Pull request merged**
