### PR TITLE
start and end date support for every (and more)

### PR DESCRIPTION
**Pull request by elmurci**
Hi!
First of all, thanks for this awesome module. It's great.
Due to my project needs, I have been forced to fork and add a couple of changes:

- every: start and end date support for job executions added, jobs created with every will only run in the date-time interval (if) given. This is helpful as it saves calls to external api's.
- Configuration file conf.js created
- single job types: two jobs with same name but different data will generate two separate records.

Thanks

### CODE REVIEW

**Comment by ilanbiala** [comment]
@rschmukler do you think we can get the start and end dates merged in at least, because those are really useful features.

**Comment by ilanbiala** [comment]
@droppedoncaprica @elmurci is everything working, or do things still need to be tidied up before @rschmukler merges?

**Comment by elmurci** [comment]
I've been using it for a while with no isses, but it would be good if someone could test it as well...

**Comment by droppedoncaprica** [comment]
Honestly for my tastes, I'd like to see each change broken out to its own PR (kind of nit-picky, I know).  

I'm down for the changes for the most part, but I'd be hesitant to merge them all of them at once.  If there are issues down the line, having each of the changes split up into their own logical commits makes it easier to spot the regression (if it ends up happening).  Just my $0.02 though.  

I do need to do some additional testing work on this soon (as the integration tests aren't catching issues they should be).  I'll probably look at it tomorrow (busy tonight), I'll take a close look at this PR when I work on that.

**Comment by rschmukler** [comment]
Sorry on the delayed response. @droppedonjapan is spot on, the reason I haven't gotten to this is that it's a lot of changes, not all of which I'm sure should be merged. I'm open to the start/end date stuff, but please break it into its own PR.

**Comment by elmurci** [comment]
Hi guys,

It's been 2 months since I sent this PR. As I had no clear feedback on it, I have been since working adding new features required by my current project (a logging feature and a dashboard) and I don't think I am going to have the time to 'go back' and work on my initial PR...

Sorry!

**Comment by ilanbiala** [comment]
@rschmukler do you think you can split up this PR into commits and add in these features?

**Comment by whmountains** [comment]
I'm not sure if it means anything, but I second this feature request.

**Comment by droppedoncaprica** [comment]
@elmurci @ilanbiala @rschmukler If no one else wants to, I can look at pulling the start/ end time changes out.  Might take a minute until it's finished though.

**Comment by ilanbiala** [comment]
@rschmukler would you prefer that someone else separates this, or can @droppedoncaprica create two different PRs out of this? I think there are some merge conflicts now because of the formatting and cleanup changes I made, so for whoever creates the PRs, please try to be consistent with the style there.

**Comment by nwkeeley** [comment]
I agree with breaking this PR out into more modularized pull requests.

**Comment by ilanbiala** [comment]
@droppedoncaprica have you started separating this PR into 2 PRs? I don't think we should leave this code to die, because it is very useful.

**Comment by elmurci** [comment]
I am sharing all the changes I am doing due to my project needs in case you want to have a go...
https://github.com/elmurci/agenda-n

**Comment by rschmukler** [comment]
@ilanbiala basically I am open to the `startDate` `endDate` aspects of the code being added into agenda. I think that it's a useful feature.

The general refactor and creation of the `conf.js` file overly abstracts / obfuscates things for my taste. If someone wants to submit a PR with the startDate / endDate aspects of this, I'd happily merge it. Please make sure to also write tests.

**Comment by ilanbiala** [comment]
@elmurci is that something you can do since you just need to revert the `conf.js` changes in your branch and submit a PR?

**Comment by droppedoncaprica** [comment]
@ilanbiala I've got the start and end date halfway implemented, I've just been super lazy about finishing what I have.  Sorry!  X'D

Seriously though, I've got to do some server work tonight so I'll crack this open and see if I can finish it up.

**Comment by ilanbiala** [comment]
@droppedoncaprica no rush, thanks for the great contribution! I can review a PR when you put all the code together.

**Comment by leonardlin** [comment]
Closing because it was implemented with PR: https://github.com/agenda/agenda/pull/361

**Pull request closed without merging**
