### PR TITLE
Mongoskin Removed

### PR DESCRIPTION
**Pull request by lafama**
Remove mongoskin and added mongojs https://github.com/mafintosh/mongojs.
All test are running except 2

### CODE REVIEW

**Comment by jakeorr** [comment]
Was there a reason that you did not go with the [official Mongo Nodejs driver](https://github.com/mongodb/node-mongodb-native)?

**Comment by gpdeedler** [comment]
It seems to solve the mongoskin dependency issue but it failed to connect to the db for me.  Here is the errors it gave:
MongoError: auth failed
    at Function.MongoError.create (/Users/mine/Documents/AgendaTest/Modulus/AgendaTestServices/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/mine/Documents/AgendaTest/Modulus/AgendaTestServices/node_modules/mongodb-core/lib/topologies/server.js:754:66
    at Callbacks.emit (/Users/mine/Documents/AgendaTest/Modulus/AgendaTestServices/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/Users/mine/Documents/AgendaTest/Modulus/AgendaTestServices/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/Users/mine/Documents/AgendaTest/Modulus/AgendaTestServices/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by lafama** [comment]
@gpdeedler Check the connection string to your mongodb server. Seems it requires authorisation. or this could be the problem
```Attention MongoDB 3 users: In MongoDB 3 the default auth mechanism is ScramSHA1 not MongoCR (the default auth mechanism in mongojs). When connecting to an auth enabled MongoDB 3 instance providing the authMechanism option value 'ScramSHA1' is mandatory!```
  
@akeorr mongojs was easier to work with

**Comment by jakeorr** [comment]
It seems to me that removing the layer of third party dependencies and working with the native mongo driver directly would be worth it. I'm not very familiar with mongojs specificially, but I'm not sure how much this project would gain by switching out mongoskin for a different third party module. I am concerned about running into similar problems with mongojs to what we have seen with mongoskin.

**Comment by nevf** [comment]
There is already a port to the mongodb-native v2.0 driver that I did and is forked here https://github.com/classdojo/agenda by Liam Don

**Comment by lafama** [comment]
@nevf  i did not use it because most of the provided tests were not passing. is that why you have commented them out?

**Comment by nevf** [comment]
@lafama I didn't update the tests. I assume Liam would have done this in his fork. It was updated 3 days ago, maybe the tests are working now.

**Comment by rschmukler** [comment]
@classdojo any thoughts on a PR for your fork? I'd love to switch over to mongo native.

**Comment by liamdon** [comment]
Sorry for the delay @rschmukler, we now have a proper PR for this: #205

**Pull request closed without merging**
