### PR TITLE
0.6.29

### PR DESCRIPTION
**Pull request by coty-crg**
I pulled from https://github.com/rschmukler/agenda/releases/tag/0.6.28 and branched off, made some fixes in my own branch and called it version 0.6.29.

This pull request would add in callbacks to the Agenda.prototype.schedule function, so large scale applications (like the one I was working on) can know when the mongo operations required by the agenda module are complete before continuing logic.

### CODE REVIEW

**Comment by loris** [comment]
This is great!
- You should resolve the version number conflict, Agenda is already `0.7.2`
- I would go ahead and add the same callback to `Agenda.prototype.every` and `Agenda.prototype.now` for consistency

**Comment by loris** [comment]
@coty-crg: that PR adding callbacks to `now`, `every` and `schedule` would be pretty handy, I could pull it for you (already using it on my fork) if you don’t have time.

**Comment by mgregson** [comment]
This seems to have been abandoned for a bit - I've gone ahead and resolved the conflicts, made the suggested changes to `now` and `every` (I need them as well), and patched what looks to be a bug in callback handling. The result is in PR#224. I've preserved @coty-crg's commits in there as well, for attribution.

**Comment by rschmukler** [comment]
Closing this as #224 was merged. Thanks and sorry for the delay!

**Pull request closed without merging**
